# Generated by Django 4.0.3 on 2022-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_userprofile_post_friendrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
