# Generated by Django 4.0.3 on 2022-04-01 17:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_recentsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearch',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
