# Generated by Django 4.0.2 on 2022-03-09 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_friendrequst_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='network_friendrequest_unique_relationships'),
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(check=models.Q(('from_user', django.db.models.expressions.F('to_user')), _negated=True), name='network_friendrequest_prevent_self_follow'),
        ),
    ]
