# Generated by Django 4.0.3 on 2022-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_recentsearch_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='No Bio...', max_length=101),
        ),
    ]
