# Generated by Django 4.0.2 on 2022-03-09 14:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='network_friendrequest_prevent_self_follow',
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.CheckConstraint(check=models.Q(('from_user', django.db.models.expressions.F('to_user')), _negated=True), name='network_friendrequest_prevent_self_friending'),
        ),
    ]
