# Generated by Django 4.0.2 on 2022-03-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
