# Generated by Django 4.0.2 on 2022-03-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_friendrequest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(blank=True, default='No bio...', max_length=64),
        ),
    ]
