# Generated by Django 4.0.2 on 2022-03-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_userprofile_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='bio',
        ),
    ]
