# Generated by Django 4.0.2 on 2022-03-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_rename_description_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(default='static/network/images/default-profile-icon.jpg', upload_to=''),
        ),
    ]
