# Generated by Django 4.0.2 on 2022-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_userprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default_icon_2.png', null=True, upload_to=''),
        ),
    ]
